# Generated by Django 5.2.17 on 2026-10-01 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=40, unique=True)),
                ("quote_date", models.DateField()),
                ("to_name", models.CharField(blank=True, max_length=120)),
                ("to_company", models.CharField(max_length=160)),
                ("to_address", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=200)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("intro", models.TextField(blank=True)),
                ("fob", models.CharField(blank=True, max_length=160)),
                ("delivery", models.CharField(blank=True, max_length=160)),
                ("terms", models.CharField(blank=True, max_length=160)),
                ("closing", models.TextField(blank=True)),
                ("signer_name", models.CharField(max_length=120)),
                ("signer_title", models.CharField(blank=True, max_length=120)),
                ("lines", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("po_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": 'django"."quotes_quote',
                "ordering": ["-created_at"],
            },
        ),
    ]
